---
deployment:
  tasks:
    # Work directly in the repository directory
    - cd /home/pinecut4youco/repositories/mcp-shipping
    - /usr/local/bin/npm install --production
    - /usr/local/bin/npx tsc