---
deployment:
  tasks:
    # Just copy files, no build commands
    - /bin/cp -R /home/pinecut4youco/repositories/mcp-shipping/* /home/pinecut4youco/mcp-shipping/
    - /bin/cp /home/pinecut4youco/repositories/mcp-shipping/.* /home/pinecut4youco/mcp-shipping/ 2>/dev/null || true